// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Use PostgreSQL schema if DATABASE_URL is a PostgreSQL URL, otherwise SQLite
const isPg = process.env["DATABASE_URL"]?.startsWith("postgres");

export default defineConfig({
  schema: isPg ? "prisma/schema.pg.prisma" : "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});

